table olist_sellers_dataset
	lineageTag: 6483c515-74b7-4307-be1b-e16f022c5175

	column seller_id
		dataType: string
		lineageTag: 9bb23bd6-4b91-468b-8242-91e2f9cc092f
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column seller_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: f42d97e8-daa1-4a7e-8bb6-06222fd5e0dd
		summarizeBy: none
		sourceColumn: seller_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column seller_city
		dataType: string
		lineageTag: ce211928-90c0-4d48-b543-e484fbb1e0c6
		summarizeBy: none
		sourceColumn: seller_city

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 596b2f9d-2350-4dfd-b4ab-72ab030851b4
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	column seller_id_short = left(olist_sellers_dataset[seller_id], 8)
		lineageTag: fd8139c4-3ad9-48a1-93d7-5f4a91c9570b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition olist_sellers_dataset = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\Trainee\Desktop\Portfolio Projekt\Dataset - CSV Files\olist_sellers_dataset.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"seller_id", type text}, {"seller_zip_code_prefix", Int64.Type}, {"seller_city", type text}, {"seller_state", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

