table olist_products_dataset
	lineageTag: 335992dc-00b4-4dae-ac58-85f6032cf495

	column product_id
		dataType: string
		lineageTag: e166a4e0-a3d4-4fff-ab7c-d1d3e746c371
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: double
		formatString: 0
		lineageTag: 229d822d-509f-4b99-9e47-30880146d5de
		summarizeBy: none
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: double
		formatString: 0
		lineageTag: 1af51adb-1b0b-4f1d-adb4-132e40e3bdbc
		summarizeBy: none
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: double
		formatString: 0
		lineageTag: fdb33a58-7872-49f1-8d67-63fd5d341d28
		summarizeBy: none
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: 88e722e6-2be8-47ca-845c-01c3a82a89a4
		summarizeBy: none
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 8d5f0d03-6c5d-4ea8-b0d9-971cccbd518b
		summarizeBy: none
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: b53c376c-838a-4d49-b12a-5e7f4ff12f61
		summarizeBy: none
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: 32abaff6-73aa-403c-96a9-9cb686cb5a82
		summarizeBy: none
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: 37ce0d3f-9862-4158-a15b-ecf0bf997855
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	partition olist_products_dataset = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\Trainee\Desktop\Portfolio Projekt\Dataset - CSV Files\olist_products_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"product_id", type text}, {"product_category_name", type text}, {"product_name_lenght", Int64.Type}, {"product_description_lenght", Int64.Type}, {"product_photos_qty", Int64.Type}, {"product_weight_g", Int64.Type}, {"product_length_cm", Int64.Type}, {"product_height_cm", Int64.Type}, {"product_width_cm", Int64.Type}}),
				    #"Zusammengeführte Abfragen" = Table.NestedJoin(#"Geänderter Typ", {"product_category_name"}, product_category_name_translation, {"product_category_name"}, "product_category_name_translation", JoinKind.LeftOuter),
				    #"Erweiterte product_category_name_translation" = Table.ExpandTableColumn(#"Zusammengeführte Abfragen", "product_category_name_translation", {"product_category_name_english"}, {"product_category_name_translation.product_category_name_english"}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Erweiterte product_category_name_translation",{"product_category_name"}),
				    #"Umbenannte Spalten" = Table.RenameColumns(#"Entfernte Spalten",{{"product_category_name_translation.product_category_name_english", "product_category_name"}}),
				    #"Ersetzter Wert - null" = Table.ReplaceValue(#"Umbenannte Spalten",null,"Unknown",Replacer.ReplaceValue,{"product_category_name"}),
				    #"Ersetzter Wert" = Table.ReplaceValue(#"Ersetzter Wert - null",null,0,Replacer.ReplaceValue,{"product_name_lenght"}),
				    #"Ersetzter Wert1" = Table.ReplaceValue(#"Ersetzter Wert",null,0,Replacer.ReplaceValue,{"product_description_lenght"}),
				    #"Ersetzter Wert2" = Table.ReplaceValue(#"Ersetzter Wert1",null,0,Replacer.ReplaceValue,{"product_photos_qty"})
				in
				    #"Ersetzter Wert2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

