table olist_order_reviews_dataset
	lineageTag: bd933c8b-34ed-4f4c-b79e-fc27924ffeed

	column review_id
		dataType: string
		lineageTag: f30e7270-beef-4012-99f7-cee8b56a7ad9
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 21c501a6-2858-4c21-a4ca-2bc65e537862
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 910b4acc-61dc-4a46-89ab-2370a27628d6
		summarizeBy: none
		sourceColumn: review_score

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column review_comment_title
		dataType: string
		lineageTag: e4b30fb7-db8d-4785-8e20-2093af3f86b9
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: a32f8982-b687-4bc3-8b82-05e3a006d08a
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dbcdb49e-ed15-4ba7-9156-5663fefb0f5d
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 72834d89-a5d9-431e-8961-aab946fedea1
			defaultHierarchy: LocalDateTable_7a6a32a7-3a04-4a76-94fb-215cb5896895.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: fc47c363-144b-4c1e-8469-1cb77c124bae
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 7d4a50c8-6ea6-474a-9b9f-37e8028f3c9b
			defaultHierarchy: LocalDateTable_ed5d2ac4-aef0-4e6c-baae-b75bef160260.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	partition olist_order_reviews_dataset = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\Trainee\Desktop\Portfolio Projekt\Dataset - CSV Files\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Geänderter Typ"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

