table product_category_name_translation
	lineageTag: 9983cbb0-2fdf-4db8-8156-99c173aaf7cb

	column product_category_name
		dataType: string
		lineageTag: c82f1e71-ff10-466a-965c-01964b01da2a
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_category_name_english
		dataType: string
		lineageTag: 1fffa345-833f-4565-bbbf-a751d8c28bb3
		summarizeBy: none
		sourceColumn: product_category_name_english

		annotation SummarizationSetBy = Automatic

	partition product_category_name_translation = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\Trainee\Desktop\Portfolio Projekt\Dataset - CSV Files\product_category_name_translation.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(Quelle,{{"Column1", type text}, {"Column2", type text}}),
				    #"Höher gestufte Header" = Table.PromoteHeaders(#"Geänderter Typ", [PromoteAllScalars=true]),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"product_category_name", type text}, {"product_category_name_english", type text}})
				in
				    #"Geänderter Typ1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

